# Generated by Django 4.2 on 2024-12-17 09:33

import bot.models
import bot.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='full name')),
                ('full_name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('full_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('username_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('username_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, validators=[bot.validators.phone_number_validator], verbose_name='phone number')),
                ('user_lang', models.CharField(blank=True, max_length=10, null=True, verbose_name='user language')),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='telegram id')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='telegram username')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', bot.models.CustomUserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
