# Generated by Django 4.2 on 2024-12-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_reminder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_lang',
        ),
    ]
